### ISSUE TITLE
Better screenshot

### ISSUE THREAD

**Issue by rodica-andronache** [Codeinwp/llorix-one#11]
@ineagu aici ma gandeam in screenshot sa scriem ceva de zerif. gen 'de la cei care au facut zerif' sau ceva. Ti se pare o idee buna?

**Comment by ineagu** [comment]
da

2015-10-14 21:20 GMT+09:00 Rodica-Elena Andronache <notifications@github.com
>:

> @ineagu <https://github.com/ineagu> aici ma gandeam in screenshot sa
> scriem ceva de zerif. gen 'de la cei care au facut zerif' sau ceva. Ti se
> pare o idee buna?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/Codeinwp/llorix-one/issues/11>.
>



-- 
Ionut Neagu
http://themeisle.com | http://codeinwp.com | http://ionutn.com
