### ISSUE TITLE
Bottom link leads to Parallax One page on Themeisle instead of Llorix

### ISSUE THREAD

**Issue by abaicus** [Codeinwp/llorix-one#44]
![image](https://cloud.githubusercontent.com/assets/15010186/12845443/9517463c-cc0e-11e5-8cd6-271cf6307b89.png)

The links leads to http://themeisle.com/themes/parallax-one/ instead of  http://themeisle.com/themes/llorix-one/

**Comment by rodica-andronache** [comment]
I don't think it's using the latest version
